# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import ast
import json
from collections.abc import Sequence
from typing import TYPE_CHECKING

import regex as re

from vllm.entrypoints.chat_utils import make_tool_call_id
from vllm.entrypoints.openai.engine.protocol import (
    DeltaFunctionCall,
    DeltaMessage,
    DeltaToolCall,
    ExtractedToolCallInformation,
    FunctionCall,
    ToolCall,
)
from vllm.logger import init_logger
from vllm.tool_parsers.abstract_tool_parser import ToolParser

if TYPE_CHECKING:
    from vllm.entrypoints.openai.chat_completion.protocol import ChatCompletionRequest
    from vllm.tokenizers import TokenizerLike

logger = init_logger(__name__)

# Solar Open tool call ids are 10 characters of [a-z0-9], generated by the
# model itself (the chat template instructs the model to do so).
_TOOL_CALL_ID_PATTERN = re.compile(r"^[a-z0-9]{10}$")


class SolarOpenToolParser(ToolParser):
    """Tool call parser for Solar Open models (e.g. upstage/Solar-Open-100B).

    Parses the format::

        <|tool_calls|><|tool_call:begin|>{id}<|tool_call:name|>{name}\\
        <|tool_call:args|>{json-args}<|tool_call:end|>...<|calls|>

    where ``{id}`` is a model-generated 10-character ``[a-z0-9]`` tool call
    id and ``<|calls|>`` is an EOS token (so it normally never appears in
    the decoded text). Multiple ``<|tool_call:begin|>...<|tool_call:end|>``
    blocks may follow each other for parallel tool calls.

    All the structural markers are single tokens with ``special=False``, so
    they survive detokenization with default sampling parameters. Turn
    separators (``<|end|>``, ``<|flush|>``, ``<|begin|>assistant``) that may
    precede the tool-call section are swallowed and never surfaced as
    content.

    This parser is designed to be used together with
    ``--reasoning-parser solar_open``, which strips the reasoning block and
    hands the response body (starting at ``<|tool_calls|>``) to this parser.

    Streaming uses a state machine with a suffix hold-back: trailing bytes
    that could be the prefix of an upcoming marker are kept in the buffer,
    because vLLM's incremental detokenizer can split a single marker
    token's text across delta boundaries. Argument text is streamed as-is;
    the Python-literal fallback of ``_normalize_args`` only applies to the
    non-streaming path, since already-streamed chunks cannot be rewritten.
    """

    TOOL_CALLS = "<|tool_calls|>"
    TOOL_CALL_BEGIN = "<|tool_call:begin|>"
    TOOL_CALL_NAME = "<|tool_call:name|>"
    TOOL_CALL_ARGS = "<|tool_call:args|>"
    TOOL_CALL_END = "<|tool_call:end|>"
    CALLS = "<|calls|>"

    # Turn-structure markers that may interleave with content and must not
    # be surfaced to the client.
    END = "<|end|>"
    FLUSH = "<|flush|>"
    BEGIN = "<|begin|>"
    _TRANSITION_ROLE = "assistant"

    # Streaming state machine states.
    _STATE_WAITING = "waiting"
    _STATE_AFTER_BEGIN = "after_begin"
    _STATE_READING_ID = "reading_id"
    _STATE_READING_NAME = "reading_name"
    _STATE_READING_ARGS = "reading_args"

    def __init__(self, tokenizer: "TokenizerLike", *args, **kwargs):
        super().__init__(tokenizer, *args, **kwargs)
        self._reset_stream_state()

        tc_begin = re.escape(self.TOOL_CALL_BEGIN)
        tc_name = re.escape(self.TOOL_CALL_NAME)
        tc_args = re.escape(self.TOOL_CALL_ARGS)
        tc_end = re.escape(self.TOOL_CALL_END)
        self.tool_call_pattern = re.compile(
            rf"{tc_begin}(.*?){tc_name}(.*?){tc_args}(.*?){tc_end}",
            re.DOTALL,
        )
        self.structural_tag_pattern = re.compile(
            rf"(?:{re.escape(self.TOOL_CALLS)}"
            rf"|{re.escape(self.CALLS)}"
            rf"|{re.escape(self.END)}"
            rf"|{re.escape(self.FLUSH)}"
            rf"|{re.escape(self.BEGIN)}{self._TRANSITION_ROLE})"
        )

    @staticmethod
    def _normalize_tool_call_id(tool_call_id: str) -> str:
        """Return the model-emitted id if well-formed, else a fresh one."""
        tool_call_id = tool_call_id.strip()
        if _TOOL_CALL_ID_PATTERN.match(tool_call_id):
            return tool_call_id
        return make_tool_call_id(id_type="solar_open")

    def _unique_tool_call_id(self, tool_call_id: str, seen: set[str]) -> str:
        """Normalize the id and ensure it is unique within the response.

        With greedy sampling the model's "random" ids can collapse to the
        same digit sequence for parallel calls; duplicate ids would break
        clients that key tool results by id.
        """
        tool_call_id = self._normalize_tool_call_id(tool_call_id)
        while tool_call_id in seen:
            tool_call_id = make_tool_call_id(id_type="solar_open")
        seen.add(tool_call_id)
        return tool_call_id

    @staticmethod
    def _normalize_args(raw_args: str) -> str:
        """Normalize the raw arguments text to a JSON string.

        The model is prompted to emit a JSON object, but fall back to a
        Python-literal parse (e.g. single-quoted dicts) before giving up and
        returning the raw text so malformed output still round-trips.
        """
        try:
            return json.dumps(json.loads(raw_args), ensure_ascii=False)
        except (json.JSONDecodeError, RecursionError):
            pass
        try:
            parsed = ast.literal_eval(raw_args)
        except (ValueError, SyntaxError, RecursionError, MemoryError):
            return raw_args
        if isinstance(parsed, (dict, list)):
            return json.dumps(parsed, ensure_ascii=False)
        return raw_args

    def extract_tool_calls(
        self,
        model_output: str,
        request: "ChatCompletionRequest",
    ) -> ExtractedToolCallInformation:
        try:
            return self._extract_tool_calls(model_output)
        except Exception:
            logger.exception("Error in extracting tool call from response.")
            return ExtractedToolCallInformation(
                tools_called=False, tool_calls=[], content=model_output or None
            )

    def _extract_tool_calls(self, model_output: str) -> ExtractedToolCallInformation:
        if (
            self.TOOL_CALL_BEGIN not in model_output
            and self.TOOL_CALLS not in model_output
        ):
            return ExtractedToolCallInformation(
                tools_called=False, tool_calls=[], content=model_output or None
            )

        tool_calls: list[ToolCall] = []
        seen_ids: set[str] = set()
        for match in self.tool_call_pattern.finditer(model_output):
            tool_call_id, func_name, raw_args = match.groups()
            tool_calls.append(
                ToolCall(
                    id=self._unique_tool_call_id(tool_call_id, seen_ids),
                    type="function",
                    function=FunctionCall(
                        name=func_name.strip(),
                        arguments=self._normalize_args(raw_args),
                    ),
                )
            )

        # Content is the text before the tool-call section, with trailing
        # turn-structure markers stripped.
        section_starts = [
            idx
            for idx in (
                model_output.find(self.TOOL_CALLS),
                model_output.find(self.TOOL_CALL_BEGIN),
            )
            if idx != -1
        ]
        content = model_output[: min(section_starts)] if section_starts else ""
        content = self.structural_tag_pattern.sub("", content)

        return ExtractedToolCallInformation(
            tools_called=len(tool_calls) > 0,
            tool_calls=tool_calls,
            content=content or None,
        )

    def _reset_stream_state(self) -> None:
        """Reset streaming-only fields. Safe to call from ``__init__`` and
        from the start of every new stream (detected via empty
        ``previous_text``)."""
        self._stream_buffer: str = ""
        self._stream_state: str = self._STATE_WAITING
        self._stream_tool_call_id: str = ""
        self._stream_seen_ids: set[str] = set()

    @staticmethod
    def _holdback_suffix(buf: str, sentinels: tuple[str, ...]) -> int:
        """Return the number of trailing bytes of ``buf`` that are a proper,
        non-empty prefix of any sentinel in ``sentinels`` — these bytes
        might complete into the sentinel once more data arrives and must
        stay in the buffer.

        Anchor on the last ``<`` (all Solar Open markers start with ``<|``)
        and only consider genuine *tail* prefixes; a letter that happens to
        appear inside a marker is NOT held back.
        """
        last_lt = buf.rfind("<")
        if last_lt == -1:
            return 0
        tail = buf[last_lt:]
        for s in sentinels:
            if len(tail) < len(s) and s.startswith(tail):
                return len(tail)
        return 0

    def extract_tool_calls_streaming(
        self,
        previous_text: str,
        current_text: str,
        delta_text: str,
        previous_token_ids: Sequence[int],
        current_token_ids: Sequence[int],
        delta_token_ids: Sequence[int],
        request: "ChatCompletionRequest",
    ) -> DeltaMessage | None:
        # Fresh stream: reset both shared (base-class) and streaming-only
        # state.
        if not previous_text:
            self.prev_tool_call_arr = []
            self.current_tool_id = -1
            self.current_tool_name_sent = False
            self.streamed_args_for_tool = []
            self._reset_stream_state()

        if delta_text:
            self._stream_buffer += delta_text

        content_out = ""
        tool_calls_out: list[DeltaToolCall] = []

        while True:
            buf = self._stream_buffer

            if self._stream_state == self._STATE_WAITING:
                markers = (
                    (self.TOOL_CALL_BEGIN, "tool_call"),
                    (self.TOOL_CALLS, "skip"),
                    (self.CALLS, "skip"),
                    (self.END, "skip"),
                    (self.FLUSH, "skip"),
                    (self.BEGIN, "begin"),
                )
                found = [
                    (buf.find(marker), marker, action)
                    for marker, action in markers
                    if buf.find(marker) != -1
                ]
                if not found:
                    # No marker yet — flush everything as content except
                    # any trailing bytes that could be the start of one.
                    hb = self._holdback_suffix(buf, tuple(m for m, _ in markers))
                    flush_end = len(buf) - hb
                    if flush_end > 0:
                        content_out += buf[:flush_end]
                        self._stream_buffer = buf[flush_end:]
                    break
                idx, marker, action = min(found)
                if idx > 0:
                    content_out += buf[:idx]
                self._stream_buffer = buf[idx + len(marker) :]
                if action == "tool_call":
                    self._stream_state = self._STATE_READING_ID
                elif action == "begin":
                    self._stream_state = self._STATE_AFTER_BEGIN
                continue

            if self._stream_state == self._STATE_AFTER_BEGIN:
                # Swallow the role name after ``<|begin|>``.
                if buf.startswith(self._TRANSITION_ROLE):
                    self._stream_buffer = buf[len(self._TRANSITION_ROLE) :]
                    self._stream_state = self._STATE_WAITING
                    continue
                if self._TRANSITION_ROLE.startswith(buf):
                    # The role name is still arriving.
                    break
                # Not a role name — back to normal content handling.
                self._stream_state = self._STATE_WAITING
                continue

            if self._stream_state == self._STATE_READING_ID:
                name_idx = buf.find(self.TOOL_CALL_NAME)
                if name_idx == -1:
                    # Ids are short; wait for the complete name marker.
                    break
                self._stream_tool_call_id = self._unique_tool_call_id(
                    buf[:name_idx], self._stream_seen_ids
                )
                self._stream_buffer = buf[name_idx + len(self.TOOL_CALL_NAME) :]
                self._stream_state = self._STATE_READING_NAME
                continue

            if self._stream_state == self._STATE_READING_NAME:
                args_idx = buf.find(self.TOOL_CALL_ARGS)
                if args_idx == -1:
                    break
                func_name = buf[:args_idx].strip()
                self._stream_buffer = buf[args_idx + len(self.TOOL_CALL_ARGS) :]

                # Register a new tool call and emit the id + name delta.
                self.current_tool_id += 1
                tool_idx = self.current_tool_id
                while len(self.prev_tool_call_arr) <= tool_idx:
                    self.prev_tool_call_arr.append({"name": "", "arguments": ""})
                while len(self.streamed_args_for_tool) <= tool_idx:
                    self.streamed_args_for_tool.append("")
                self.prev_tool_call_arr[tool_idx]["name"] = func_name
                self.current_tool_name_sent = True

                tool_calls_out.append(
                    DeltaToolCall(
                        index=tool_idx,
                        id=self._stream_tool_call_id,
                        type="function",
                        function=DeltaFunctionCall(name=func_name, arguments=""),
                    )
                )
                self._stream_state = self._STATE_READING_ARGS
                continue

            if self._stream_state == self._STATE_READING_ARGS:
                end_idx = buf.find(self.TOOL_CALL_END)
                if end_idx != -1:
                    args_chunk = buf[:end_idx]
                    self._stream_buffer = buf[end_idx + len(self.TOOL_CALL_END) :]
                    self._stream_state = self._STATE_WAITING
                else:
                    hb = self._holdback_suffix(buf, (self.TOOL_CALL_END,))
                    flush_end = len(buf) - hb
                    if flush_end <= 0:
                        break
                    args_chunk = buf[:flush_end]
                    self._stream_buffer = buf[flush_end:]
                if args_chunk:
                    tool_idx = self.current_tool_id
                    self.streamed_args_for_tool[tool_idx] += args_chunk
                    self.prev_tool_call_arr[tool_idx]["arguments"] += args_chunk
                    tool_calls_out.append(
                        DeltaToolCall(
                            index=tool_idx,
                            function=DeltaFunctionCall(arguments=args_chunk),
                        )
                    )
                continue

            # Unreachable — every state above either `continue`s or `break`s.
            break

        if not content_out and not tool_calls_out:
            return None
        return DeltaMessage(
            content=content_out or None,
            tool_calls=tool_calls_out,
        )
